### ISSUE TITLE
Crash with exit code -1

### ISSUE THREAD

**Issue by ekiplier** [Siphalor/wandering-collector#8] opened 2022-04-03 18:49 UTC
This happened in Minecraft 1.17.1 and I was running the 0.13.3 version of the fabric mod loader

The latest version of Wandering Collector for Minecraft 1.17.1 is crashing my modpack. Unfortunately, it doesn't create any crash reports so the best I can do is upload the latest log. It runs with the earlier version, 1.0.2+mc1.17, just not with 1.1.1+mc1.17. My guess is that there's some incompatibility going on with some other mod.

[latest.log](https://github.com/Siphalor/wandering-collector/files/8405261/latest.log)

**Comment by Siphalor** [comment] 2022-04-30 16:46
I don't think this is caused by Wandering Collector.

I think it's caused by an incompatibility between NPC Variety and some other mod.

So I'm going to close this for now. If you can reproduce this without NPC Variety I'll reopen it :)

**Closed as completed by Siphalor** 2022-04-30 16:46 UTC
